global:
  scrape_interval: 15s  # How often to scrape targets (default is 1m)
  scrape_timeout: 10s   # How long until scraping times out (default is 10s)
  evaluation_interval: 15s  # How often to evaluate rules (default is 1m)

scrape_configs:
  - job_name: 'aggregator'
    scrape_interval: 15s  # Override the global default scrape interval
    scrape_timeout: 10s   # Override the global default scrape timeout
    metrics_path: '/metrics'
    scheme: 'http'
    follow_redirects: true
    static_configs:
      - targets: ['localhost:4000']
